FROM node:latest

LABEL author="Sathish"

WORKDIR /app 

COPY package.json /app

RUN npm install 

RUN npm install  -g nodemon

RUN npm install -g @angular/cli@1.7.4 

COPY . /app

CMD ["npm", "start"]

EXPOSE 3000